version: 2.1
jobs:
  build:
    machine:
      image: circleci/classic:latest
    steps:
      - checkout
      - run:
          name: run build file
          command: /bin/bash -x build.sh ${CIRCLE_SHA1} test
  test-cases:
    working_directory: ~/src/
    machine:
      # Ref: https://circleci.com/docs/2.0/configuration-reference/#available-machine-images
      image: ubuntu-2004:202010-01
    steps:
      - checkout:
          path: ~/src/
      - run: 
          name: Installing prerequisites
          command: |-
            node --version
workflows:
  version: 2
  build_and_test:
    jobs:
      - test-cases