version: 2.1 # CircleCI version
jobs:
  build:
    machine: # Use a Linux VM instead of docker environment
      image: ubuntu-2004:202111-01
      docker_layer_caching: false
    working_directory: ~/user # Default working directory, where your project will be cloned
    steps:
      - checkout:
          path: ~/user
      - run:
          name: Install dependencies
          command: cd src/ && npm install
      - run:
          name: Installing prerequisites
          command: |-
            docker-compose --version
      - run:
          name: Starting the docker containers
          command: |-
            cd dev-ops/ && docker-compose up -d
      - run:
          name: Running test cases
          environment:
            JEST_JUNIT_OUTPUT: reports/junit/junit.xml
          command: |-
            cd src/ &&  npm run test:integration -- --testResultsProcessor="jest-junit"
      - store_test_results:
          path: reports/junit
      - store_artifacts:
          path: reports/junit
      - run:
          name: Executing unit test cases
          command: cd src && npm run test
workflows:
  build-and-test: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - build
